version: '3.7'
services:
  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - ./redis:/bitnami/redis/data
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
  test:
    image: node:16
    working_dir: /app
    command: npm run serve
    depends_on:
      - redis
    volumes:
      - ./:/app
    ports:
      - "9000:80"
    environment:
      - PORT=80
      - BASIC_AUTH_USER=storykit
      - BASIC_AUTH_PASS=testpass
      - REDIS_URL=redis://redis:6379